// CS F363: Compiler Construction
// Group no. 37
// 2022B4A70496P Garvit Singhal
// 2023A7PS0577P Raunit Raj
// 2023A7PS0613P Rishita Sachan
// 2023A7PS0622P Ranvijay Tanwar
// 2023A7PS0655P Rishabh Sharma
// 2023A7PS0605P Aayush Garg

    /***********************************************************
 * driver.c
 * * The main entry point for the compiler.
 * This file implements the menu-driven interface, validates
 * command-line arguments, and acts as the orchestrator
 * between the Lexical Analyzer and the Syntax Analyzer.
 ***********************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#include "lexer.h"
#include "parser.h"

int main(int argc, char *argv[])
{
    // =======================================================
    // 1. Display Implementation Status
    // =======================================================

    printf("\n=======================================================\n");
    printf("IMPLEMENTATION STATUS:\n");
    printf("(a) FIRST and FOLLOW sets manually computed and mapped to Parse Table.\n");
    printf("(b) Both lexical and syntax analysis modules fully implemented.\n");
    printf("(c) Panic Mode Error Recovery implemented for Lexical and Syntax errors.\n");
    printf("(d) Parse tree constructs perfectly for syntactically correct code.\n");
    printf("(e) We have tried our best to prevent printing repeated errors but it happens sometimes.\n");
    printf("(f) Both modules work with all the testcases provided.\n");
    printf("=======================================================\n\n");

    // =======================================================
    // 2. Command Line Argument Validation
    // =======================================================
    // ./stage1exe testcase.txt parsetreeOutFile.txt
    if (argc != 3) {
        printf("Error: Incorrect number of arguments.\n");
        printf("Usage: ./stage1exe <testcase.txt> <parsetreeOutFile.txt>\n");
        return 1;
    }

    // =======================================================
    // 3. Global Initializations
    // =======================================================
    // We initialize the keyword symbol table and the LL(1) parse table
    // once at startup so we don't waste CPU cycles rebuilding them on every menu press.
    populate_keywords();
    initParseTable();

    int choice;

    // =======================================================
    // 4. Main Menu Loop
    // =======================================================
    while (1) {
        printf("\n===== Compiler Driver Menu =====\n");
        printf("0 : For exit\n");
        printf("1 : For removal of comments - print the comment free code on the console\n");
        printf("2 : For printing the token list (on the console) generated by the lexer\n");
        printf("3 : For parsing to verify syntactic correctness and printing the parse tree\n");
        printf("4 : For printing the total time taken by lexer and parser\n");
        printf("Enter option choice: ");

        // Safely capture user input and flush the buffer to prevent infinite loops on bad input
        if (scanf("%d", &choice) != 1) {
            while (getchar() != '\n');
            printf("Invalid input. Please enter a number.\n");
            continue;
        }

        switch (choice) {

            case 0:
                printf("Exiting compiler...\n");
                return 0;

            case 1:
                // This option just strips comments and saves to a clean file.
                // The function internally prints the clean code to the console.
                removeComments(argv[1], "clean_source.txt");
                break;

            case 2:
            {
                // Lexical Analysis: Just tokenize and print.
                FILE *fp = fopen(argv[1], "r");
                if (!fp) {
                    printf("Error opening file: %s\n", argv[1]);
                    break;
                }

                init_buffers(fp);
                Token t;

                // printing the token list
                printf("\n%-10s %-25s %-20s\n", "Line No.", "Lexeme", "Token Name");
                printf("------------------------------------------------------------\n");

                while ((t = get_next_token()).type != TK_EOF) {
                    // We don't print errors or comments here, just the valid tokens
                    if (t.type != TK_ERROR && t.type != TK_COMMENT) {
                        printf("%-10d %-25s %-20s\n", t.line, t.lexeme, tokenNames[t.type]);
                    }
                }

                fclose(fp);
                break;
            }

            case 3:
            {
                // Full Compilation Phase: Lexical + Syntax Analysis
                printf("\nInvoking Parser...\n");

                // The parser drives the lexer internally via get_next_valid_token()
                parseTreeNode *root = parseInputSourceCode(argv[1]);

                if (errorCount > 0) {
                    // If Panic Mode caught errors, dump them to the console
                    printf("\nParsing finished with ERRORS.\n");
                    printErrorsToConsole();
                    printErrorsToFile(argv[1]);
                }
                else if (root != NULL) {
                    // Success case: Exact string match requested by the rubric
                    printf("\nInput source code is syntactically correct...........\n");

                    // Write the N-ary inorder traversal to the specified output file
                    printParseTree(root, argv[2]);
                    printf("Parse tree successfully written to %s\n", argv[2]);
                }
                else {
                    // Failsafe in case of a fatal memory or file error
                    printf("\nParser failed fatally. No tree generated.\n");
                }
                break;
            }

            case 4:
            {
                // Time benchmarking
                clock_t start_time, end_time;
                double total_CPU_time, total_CPU_time_in_seconds;

                start_time = clock();

                // Invoking parseInputSourceCode automatically runs BOTH the lexer
                // (for twin buffer I/O and tokenizing) and the parser (for tree building).
                parseTreeNode *root = parseInputSourceCode(argv[1]);

                end_time = clock();

                // Calculate ticks and seconds
                total_CPU_time = (double) (end_time - start_time);
                total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;

                printf("\n--- Execution Time ---\n");
                printf("Total CPU Time (ticks)   : %f\n", total_CPU_time);
                printf("Total CPU Time (seconds) : %f\n", total_CPU_time_in_seconds);
                printf("----------------------\n");
                break;
            }

            default:
                printf("Invalid option. Please try again.\n");
        }
    }
}
