// CS F363: Compiler Construction
// Group no. 37
// 2022B4A70496P Garvit Singhal
// 2023A7PS0577P Raunit Raj
// 2023A7PS0613P Rishita Sachan
// 2023A7PS0622P Ranvijay Tanwar
// 2023A7PS0655P Rishabh Sharma
// 2023A7PS0605P Aayush Garg

/***********************************************************
 * lexerDef.h
 *
 * Data definitions and structures for the Lexical Analyzer.
 * This file defines the Token types, specific Lexical Error
 * flags, and the core Token structure passed to the Parser.
 ***********************************************************/

#ifndef LEXERDEF_H
#define LEXERDEF_H

// ==========================================
// Token Type Enumeration
// ==========================================
// Maps every valid terminal symbol in our grammar to an integer ID.

typedef enum {
    // Primitives and Identifiers
    TK_NUM, TK_RNUM, TK_ID, TK_FIELDID, TK_FUNID, TK_RUID, TK_MAIN,

    // Operators and Punctuation
    TK_ASSIGNOP, TK_AND, TK_OR, TK_NOT, TK_LT, TK_LE, TK_EQ, TK_GT, TK_GE, TK_NE,
    TK_PLUS, TK_MINUS, TK_MUL, TK_DIV, TK_COMMA, TK_SEM, TK_COLON, TK_DOT,
    TK_OP, TK_CL, TK_SQL, TK_SQR,

    // Keywords
    TK_WITH, TK_PARAMETERS, TK_END, TK_WHILE, TK_UNION, TK_ENDUNION,
    TK_DEFINETYPE, TK_AS, TK_TYPE, TK_GLOBAL, TK_PARAMETER, TK_LIST,
    TK_INPUT, TK_OUTPUT, TK_INT, TK_REAL, TK_ENDWHILE, TK_IF, TK_THEN,
    TK_ENDIF, TK_READ, TK_WRITE, TK_RETURN, TK_CALL, TK_RECORD,
    TK_ENDRECORD, TK_ELSE,

    // Special internal tokens
    TK_ERROR, TK_EOF, TK_COMMENT
} TokenType;

// ==========================================
// Lexical Error Flags
// ==========================================
// Used by the parser's panic mode to print specific error messages
typedef enum {
    ERR_NONE,               // Valid token, no error
    ERR_ID_LONG,            // Variable identifier > 20 characters ir <2 characters
    ERR_FUNID_LONG,         // Function identifier > 30 characters
    ERR_UNKNOWN_SYMBOL,     // Invalid single character
    ERR_UNKNOWN_PATTERN     // Invalid combined pattern
} ErrorType;

// ==========================================
// Token Information Structure (tokenInfo)
// ==========================================
// This is the primary data packet generated by the Lexer.
typedef struct {
    TokenType type;         // The enumerated token ID
    char lexeme[256];       // The actual string extracted from the source code
    int line;               // Line number where the token was found
    ErrorType err;          // Carries the specific lexical error flag if type == TK_ERROR

    // We use a union here to save memory. This is valid because a token will never be both an int and a float
    union {
        int intVal;         // Computed integer value (if TK_NUM)
        float realVal;      // Computed floating-point value (if TK_RNUM)
    } attr;
} Token;

// ==========================================
// Buffer Configuration
// ==========================================
// We use a 4KB chunk size for the twin buffer to optimize disk I/O reads.
#define BUFFER_SIZE 4096

#endif
